[package]
name = "infojenn"
version = "0.1.0"
edition = "2021"

[dependencies]
ontolius = { version = "0.5.2", default-features = false }
anyhow = "1.0.86"

[dev-dependencies]
ontolius = { version = "0.5.2", features = ["obographs", "csr"] }
flate2 = "1.1.0"
