[package]
name = "infojenn"
version = "0.1.0-dev0"
edition = "2021"

[dependencies]
ontolius = { git = 'https://github.com/ielis/ontolius.git', tag = 'v0.3.1' }
anyhow = "1.0.86"
rayon = "1.10.0"
itertools = "0.13.0"
